# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Prof. Amine Ouazad
email: amine.ouazad@hec.ca
description: > # this means to ignore newlines until "baseurl:"
  An economist with interests in cities, real estate, finance, climate, labor, education.
  Associate professor at HEC Montreal, Canada.
  Holder of a professorship in "Real Estate and Urban Economics" sponsored by the HEC
  Foundation. Also member of the First Street Foundation Lab.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ouazad.com" # the base hostname & protocol for your site
twitter_username: amine_ouazad
github_username:  aouazad
remote_theme: thelehhman/texture
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
